# backend/services/pdf_generator.py
import time
from ..models.loan_schema import LoanApplication

def generate_sanction_letter(data: LoanApplication) -> str:
    """
    Simulates generating a PDF document and storing it, returning a mock URL.
    In a real system, this would use a library like ReportLab or FPDF.
    """
    timestamp = int(time.time())
    
    # 1. Simulate Document Content Creation
    content = f"""
    *** MOCK LOAN SANCTION LETTER - {timestamp} ***
    
    Applicant: {data.full_name or 'N/A'}
    PAN/Aadhaar: {data.pan_number or 'N/A'} / {data.aadhaar_number or 'N/A'}
    
    We are pleased to inform you that your loan application has been **{data.status.upper()}**.
    
    --- Sanctioned Terms ---
    Amount Approved: ${data.sanctioned_amount:,}
    Interest Rate: {data.interest_rate}% (Mock Rate)
    Tenure: {data.tenure_months} months
    Monthly Income: ${data.annual_income // 12:,}
    
    ***
    DISCLAIMER: This is a document generated by a prototype multi-agent AI system 
    for demonstration purposes only and has NO LEGAL VALIDITY.
    """
    
    # 2. Simulate File Storage (e.g., to an S3 bucket or local mock storage)
    filename = f"loan_sanction_{timestamp}.pdf"
    
    # For a realistic demo, you might write this content to a temporary file:
    # with open(f"temp_pdf_storage/{filename}", "w") as f:
    #     f.write(content)
    
    # 3. Return the Mock URL (to be used by the frontend)
    mock_url = f"http://127.0.0.1:8000/downloads/{filename}"
    print(f"[SERVICE] Mock PDF generated. Content:\n{content}")
    
    return mock_url